name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Check file existence 
      run: git ls-remote --heads https://github.com/vaugusto92/hello-world.git TESTE | wc -l

    - name: Make folder
      run: mkdir -p ~/path/to/artifact
      
    - name: Make artifact
      run: echo hello > ~/path/to/artifact/world.txt
    
    - name: Find file again
      run: find ~/ -type f -name "world.txt"
