name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p ~/path/to/artifact

    - run: echo hello > ~/path/to/artifact/world.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact-2
        path: ~/path/to/artifact/world.txt
