name: CI

on: push

env:
  FOO: bar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: env test
      run: echo $FOO
        
    - name: Check file existence 
      run: git ls-remote --heads https://github.com/vaugusto92/opencv-builds.git 4.6.0 | wc -l

    - name: Make folder
      run: mkdir -p ~/path/to/artifact
      
    - name: Secret example
      run: echo ${{ secrets.TEST }}
      
    - name: Make artifact
      run: echo hello > ~/path/to/artifact/$FOO
    
    - name: Find file again
      run: find ~/ -type f -name "$FOO"
