name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - run: find ~/ -type f -name "world.txt"

    - run: mkdir -p ~/path/to/artifact

    - run: echo hello > ~/path/to/artifact/world.txt
    
    - run: find ~/ -type f -name "world.txt"
