name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p ~/path/to/artifact

    - run: echo hello > ~/path/to/artifact/world.txt
    
    - run: cd ~/path/to/artifact/ && tar -czf test.tar.gz * 

    - uses: actions/upload-artifact@v3
      with:
        name: tar-artifact
        path: ~/path/to/artifact/test.tar.gz 
